### PR TITLE
added set subpixel

### PR DESCRIPTION
**Pull request by FreezyExp**
Added method to set a sub pixel
Added an example that handles 6 strings of 2 leds, updating only
specific sub-pixels and syncs the string only if needed

I found some code online that promises an accurate clock, so decided I
wanted to try it out in combination with WS2818b leds

The code still needs the ability to be set manually to a specific time.
A simple hold analog button press to forward the minutes should do
(speeding up the minutes if long pressed).

### CODE REVIEW

**Comment by FreezyExp** [comment]
Pleas wait while I debug the clock a bit ;-)

**Comment by FreezyExp** [comment]
Done, added button control to fast forward through the clock.
Also fixed the output so that it matches a standard analog 12 hour clock.

AM PM modes currently disabled, as it requires a bit more testing.

**Comment by cpldcpu** [comment]
Great example! I had actually planned to do something like this byself, but never got around doing it. Well, here it is :)

**Comment by cpldcpu** [comment]
Which file exactly?

**Pull request merged**
