### PR TITLE
LED Grouping

### PR DESCRIPTION
**Pull request by sschultewolter**
Hello Tim,

these functions should make it easier to put several successive LEDs with the same values ​​. This should save a lot of program memory with larger numbers of LEDs .

``` C
/* User Interface
*
* Input:
*         ledarray:           An array of GRB data describing the LED colors
*         number_of_leds:     The number of LEDs to write
*         pinmask (optional): Bitmask describing the output bin. e.g. _BV(PB0)
*         group:              Number of consecutive LEDs with the same value
*
* The functions will perform the following actions:
*         - Set the data-out pin as output
*         - Send out the LED data
*         - Wait 50µs to reset the LEDs
*/
void ws2812_setleds_group(struct cRGB *ledarray, uint16_t number_of_leds, uint16_t group)
{
    ws2812_setleds_group_pin(ledarray, number_of_leds, group, _BV(ws2812_pin));
}

void ws2812_setleds_group_pin(struct cRGB *ledarray, uint16_t number_of_leds, uint16_t group, uint8_t pinmask)
{
    ws2812_DDRREG |= pinmask; // Enable DDR
    for(uint8_t i = 0; i < number_of_leds; i++)
    {
        for(uint8_t j = 0; j < group; j++)
        ws2812_sendarray_mask((uint8_t*)&ledarray[i], 3, pinmask);
    }
    _delay_us(50);
}
```

### CODE REVIEW

**Comment by cpldcpu** [comment]
Hi Stefan,

Thank you for the pull request. It seems that your commit is based on a very old branch, which is currently causing a bit of a headache to me (what is new and what is old?). Also, I am pondering a bit about the best place to put the functionality right now as I don't want to put too many additional functions into the core library. May be it would be easier just to add this as an example? Let me think about it...

**Comment by sodabrew** [comment]
@sschultewolter You probably want to merge into `master` and not `testing`? Perhaps you can just switch the target branch of this PR to master? (You might need to open a new PR, though):
    _sschultewolter  wants to merge 63 commits into **testing** from master_
to
    _sschultewolter  wants to merge 63 commits into **master** from master_

Ideally your new commits would also be on a new branch, and not on your master branch, which does require a new PR, but is the best way to proceed. https://help.github.com/articles/creating-a-pull-request/ Happy to help guide you with git if you have any trouble in the process!

**Comment by cpldcpu** [comment]
@sodabrew: Ah yes, that is indeed the problem.

**Comment by usedbytes** [comment]
Is this likely to get merged? I was about to submit a pull request for very similar functionality, but sschultewolter's looks better

My proposed additions:

    +/*
    + * These functions can be used to set many LEDs to the same colour without
    + * needing a whole LED array in RAM
    + */
    +void ws2812_setleds_constant(struct cRGB *ledval, uint16_t leds);
    +void ws2812_setleds_constant_rgbw(struct cRGBW *ledval, uint16_t leds);
    +

**Comment by usedbytes** [comment]
On second thoughts, sschuletwolter's implementation can race with interrupt handlers in-between groups, which could be a deal breaker with my application.

I'll submit my PR anyway, it can always be improved upon

**Pull request closed without merging**
