### PR TITLE
revise LGT8x timing

### PR DESCRIPTION
**Pull request by jg1uaa**
different from Arduino implementation, AVR code runs same clocks
within ws2812_sendarray_mask() assembler loop because it uses OUT
instruction, not ST.

so simply replace RJMP instruction to BRID.
This instruction takes 2clocks on both AVR and LGT8x, so there is no
need to CPU-specific definition.

### CODE REVIEW

**Comment by cpldcpu** [comment]
Thank you very much!

I had to think about this for a while. BRID is a branch in dependence of the interrupt flag. Generally the interrupts are disable while this library is used. I have, however, seen some people using it with interrupts enabled in some special timing configurations. I am a bit concerned that changing to BRID instead of RJMP also on AVR would confuse a lot of people.

My suggestion would therefore be to only use BRID on LGT and stay with RJMP on AVR based on conditional compilation, just as done in the Arduino version.

**Comment by jg1uaa** [comment]
I thought that who tells for AVR or LGT to this code first. In Arduino environment, board support package sets __LGT8F__ macro and library uses #ifdef to write LGT specific code.
But this portion runs under bare metal environment and library user themselves need to set the macro. Many skilled users do that but sometimes it is forgotten. So I considered that how to run same code between AVR and LGT.

How about using BRTC instead of BRID and adding CLT instruction like this?

```
    asm volatile(
    "       ldi   %0,8  \n\t"
    "       clt         \n\t"    // <-- add here
    "loop%=:            \n\t"
    "       out   %2,%3 \n\t"    //  '1' [01] '0' [01] - re
```

There is no instruction that affects T flags in the loop so simply clear the flag before entering the loop.
This suggestion makes the object 2byte-larger but can support special (enabled interrupt) case.

**Comment by cpldcpu** [comment]
That's a good idea indeed!

**Comment by cpldcpu** [comment]
Merged, thanks a lot!

**Pull request merged**
